{% set version = "12.10.1" %}

package:
  name: trilinos
  version: {{ version }}

source:
  url: http://trilinos.csbsju.edu/download/files/trilinos-{{ version }}-Source.tar.gz
  sha256: ea8ff573bb1f452f2585950cdabe7e2c84cb35013844c58dc878c66bd4245e06

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake >=2.8.11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}
    - openblas
    - boost-cpp

  run:
    - {{ mpi }}
    - openblas
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/include/TeuchosCore_ConfigDefs.hpp
    - test -f $PREFIX/lib/libteuchoscore.{{ version }}.dylib    # [osx]
    - test -f $PREFIX/lib/libteuchoscore.so.{{ version }}       # [linux]

about:
  home: https://trilinos.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    Sandia's suite of HPC solvers and enabling technologies
  description:
    Fast, compiled object-oriented algorithms and enabling
    technologies for the solution of large-scale, complex
    multi-physics engineering and scientific problems.
  dev_url: https://github.com/trilinos/Trilinos

extra:
  recipe-maintainers:
    - wfspotz
