{% set version = "12.12.1" %}

package:
  name: trilinos
  version: {{ version }}

source:
  url: https://github.com/trilinos/Trilinos/archive/trilinos-release-12-12-1.tar.gz
  sha256: 5474c5329c6309224a7e1726cf6f0d855025b2042959e4e2be2748bd6bb49e18

build:
  number: 1004

requirements:
  build:
    - cmake >=2.8.11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}
    - openblas
    - boost-cpp
  run:
    - {{ mpi }}
    - openblas
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/include/TeuchosCore_ConfigDefs.hpp        # [unix]
    - test -f $PREFIX/lib/libteuchoscore.{{ version }}.dylib    # [osx]
    - test -f $PREFIX/lib/libteuchoscore.so.{{ version }}       # [linux]
    - if not exist %PREFIX%\\Library\\include\\TeuchosCore_ConfigDefs.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libteuchoscore.dll exit 1  # [win]

about:
  home: https://trilinos.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    Sandia's suite of HPC solvers and enabling technologies
  description:
    Fast, compiled object-oriented algorithms and enabling
    technologies for the solution of large-scale, complex
    multi-physics engineering and scientific problems.
  dev_url: https://github.com/trilinos/Trilinos

extra:
  recipe-maintainers:
    - wfspotz
    - jschueller
