appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle, win: azure}
travis:
  secure: {BINSTAR_TOKEN: 0pGseeAlC2QX91NRgGiI3c2cSyupB7Vw/aluAeQGQ63Udnbhc/INboOlzu0cHyiIbwocZMuQEwI01BkLGWBKqTnzqz2wkmapiVzaKhGuFCF9zWbMma9EyvtxH9Bvhis+H5IgezQZXTwAIaPAsoCigB4T+NzWZF2G8RG5bW3b111Sm+S+4elI+ArSBZbJXO0z93YU1ax16eIT1wwXeLhzy7JG81Y8MZk4arveRCVNpzza8UNU1Zu7a6TKyKmKWRswilnYypai2u3CNvduaaYNy48TZ0o/z1dkGc5rRplq8np4O7cnRZ68b9IFjiWq5SPHrdsbe6r8s3LFG5ikHgv1LtIDIX7mAH9q2162nAdkL8dU1l1HoCVrlaAfeix6vpOBGzeZNGMmxxK6zGLAQTGGXtrx+PY3/m0whLbjhmkbL/ifCVc3W1y/XFy6aRlHebi12rOCzRnheNKW1fzdexHcGRV03BgxZusZ+lB4dZrDB0VveplYq4NEE1jZczncFOwkXEwYw4xBaPDma5mDz01Q9rOezGvLc+9mmjVE/ywYIXd1uOzoScgLDcEB90jwgmPdlH7pqo58ZQRmCd5za5pEeemCxsTPrjdB6+NCRFZYM7E9MGf92dREWCI0e83YEMJVul00mB3QjWEBUjw5oLDFoxYiwvVdrlqmM8eFMs9yOOk=}
