version: 2

jobs:
  build_linux_c_compilergcccxx_compilergxxmpimpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergcccxx_compilergxxmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilergcccxx_compilergxxmpiopenmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergcccxx_compilergxxmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_osx_c_compilerclangcxx_compilerclangxxmpimpich:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_c_compilerclangcxx_compilerclangxxmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_osx_build.sh
  build_osx_c_compilerclangcxx_compilerclangxxmpiopenmpi:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_c_compilerclangcxx_compilerclangxxmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_osx_build.sh
  build_osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_osx_build.sh
  build_osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_osx_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_c_compilergcccxx_compilergxxmpimpich
      - build_linux_c_compilergcccxx_compilergxxmpiopenmpi
      - build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich
      - build_linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi
      - build_osx_c_compilerclangcxx_compilerclangxxmpimpich
      - build_osx_c_compilerclangcxx_compilerclangxxmpiopenmpi
      - build_osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich
      - build_osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi
